# Site settings
title: 신비로운 기술 블로그 | 개발 놀이터
description: "Arcane's Tech Blog, built with Jekyll."
url: "http://arcane-nb.github.io/"
author:
  name: "Arcane-nb"
  email: "arcane-nb@gmail.com"
  url: "https://arcane-nb.github.io"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 7
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
